FROM mysql:8.0
ENV MYSQL_ROOT_USER: root
ENV MYSQL_ROOT_PASSWORD=root!
ENV MYSQL_DATABASE=course_recommendation
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=user!
EXPOSE 3310
COPY ./ddl.sql /docker-entrypoint-initdb.d/